### ISSUE TITLE
How to extract text ?

### ISSUE THREAD

**Issue by nzhtrtlc** [Hopding/react-native-pdf-lib#2]
Hi @Hopding , i extracted the text from pdf using java for desktop app.
After this i wanted to use it in react-native then i saw your repo then thought i wont have to build my own native module.

Here is how i extracted text.
https://gist.github.com/nzhtrtlc/1373df42304fd4163bcdb958cd838a41

Can we do this in your module or provide ?

**Comment by Hopding** [comment]
Hello @nzhtrtlc,

`react-native-pdf-lib` does not currently expose any JavaScript APIs for text stripping. However, it could be implemented in the core libraries it uses for manipulating PDFs on Android and iOS. If you wish to fork the project or create a branch and add this functionality, I would welcome a Pull Request!

It certainly should be possible to do this with [PdfBox-Android](https://github.com/TomRoush/PdfBox-Android) (this is the Java library that `react-native-pdf-lib` uses under the hood on Android). Here is an [example](https://github.com/TomRoush/PdfBox-Android/blob/master/sample/src/main/java/com/tom_roush/pdfbox/sample/MainActivity.java#L212-L239). 

Of course, this will only provide the text stripping functionality on Android devices. If you also wish to provide this feature on iOS, it would be necessary to do so with [PDF-Writer](https://github.com/galkahana/PDF-Writer) (the library used under the hood for iOS). Unfortunately, this functionality does not appear to exist [out of the box](https://github.com/galkahana/PDF-Writer/issues/56). But it looks as though it has been [implemented](http://pdfhummus.com/post/156548561656/extracting-text-from-pdf-files) in the Node JS wrapper, so that could provide a starting point.

**Comment by nzhtrtlc** [comment]
@Hopding  Thanks for your answer. I don't have experince about native modules. But still i forked your repo but i don't know how can i test my code ?
There is only "test" script in npm scripts. And these test files are not really a test.
So i am confused 😕

**Comment by Hopding** [comment]
@nzhtrtlc Development on react native libraries can be a little weird. I'd like to post a detailed guide at some point. But in the meantime, what you essentially have to do is add this library to an existing react native project (created with  `react-native init`), and build that. Unfortunately, you cannot really test changes to a native library independently of a runnable project.

The reason is that this library (and any react-native library with native code) depends on modules that will only exist if the library is built in the context of a full, runnable project.

What you can do is create a new react native project, and then clone the repository for `react-native-pdf-lib` into that project's `node_modules` directory. Next run `react-native link` on that project. Then, when you make changes to the library's code, you should be able to rebuild the runnable project to see the results.

Does this make sense?

As far as the tests are concerned, don't worry about those. As you point out, there aren't any actual tests right now. I just added the Jest framework in preparation for the tests in the future.

**Comment by nzhtrtlc** [comment]
@Hopding I got it now.
I can edit your code from **node_modules** and i can see my changes using `react-native link` thanks for the tip.

Here is what i tried to do but failed.

- First, i wrote my native code in PDFLibModule.
**PDFLibModule.java**
I created method called `stripText` line between 62-94
https://gist.github.com/nzhtrtlc/e84d69d11b4bce6ed94699b6e1612e9c#file-pdflibmodule-java-L62-L94
- Second, i wrote javascript code i have no idea about what am i doing. I just tried to follow your way.
**PDFDocument.js**
I created method called `getText` line between 33-37
https://gist.github.com/nzhtrtlc/8d06ced669900deb98b02477c88ccc74#file-pdfdocument-js-L33-L37
- Third, i wrote code in react native project and try to load pdf and extract text from it.
![image](https://user-images.githubusercontent.com/17534778/32572519-8723f2ae-c4d3-11e7-92f6-3565f68923b8.png)

After i pressed `Read PDF` button it gave me an error, here is screenshot.
![image](https://user-images.githubusercontent.com/17534778/32572573-b0902518-c4d3-11e7-83ec-07dbb3ac4fdc.png)

I don't know where is my mistake but i would be very appreciate if you can add this function 
*(extract all text from pdf)*
Thanks for your help.

**Comment by Hopding** [comment]
@nzhtrtlc Nothing about your Java or JavaScript code looks incorrect. Unfortunately, I am unable to view the images you posted. If you can try to re-upload them, perhaps I can assist you further? You should also be able to just copy & paste the error. I believe React Native allows you to copy errors text from the simulator via a button on the error screen.

**Comment by nzhtrtlc** [comment]
@Hopding im in different pc right now but i can see the images.

Here is a link for image https://user-images.githubusercontent.com/17534778/32572573-b0902518-c4d3-11e7-83ec-07dbb3ac4fdc.png
if you still cant see the error text is like this:

> Attempt to invoke interface method 'java.lang.String.com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference.

getText
- PDDocumentFactory.java:47

stripText
- PDFLibModule.java:67

**Comment by Hopding** [comment]
I'm afraid I got busy and forgot about this issue. I'm going to close this for now. If anybody would like to revisit this, please feel free to reopen it. My apologies for failing to respond and having forgotten about this.

**Comment by joshien1997** [comment]
@nzhtrt Have you done it ??

**Comment by kentdev92** [comment]
Have you guys implemented extract text functionality yet?

**Comment by vinamrahalgar** [comment]
@Hopding  How to read text from PDF using getText(). Any solution?

**Comment by Vinayak006** [comment]
Any update on this?

**Comment by benbenwsh** [comment]
Have you guys done it?
