### ISSUE TITLE
OOM error with 4 pages or more

### ISSUE THREAD

**Issue by aureliopetrone** [Hopding/react-native-pdf-lib#36]
Hello @Hopding, I love your library but I have problems adding multiple pages to a document. 

When the number of pages grow I experience this error:

```
Could not invoke PDFLib.createPDF

null

Failed to allocate a 262160 byte allocation with 111440 free bytes and 108KB until OOM, max allowed footprint 536870912 growth limit 536870912
```
There is a screenshoot of the error here

https://imgur.com/a/xCifFo0

On some devices, I can add at max 3 pages, on some others 4-5. But I need to add up to 20 pages to a document. The document is really light, there are only text and lines (1px height rectangles) and one single image in the first page (a very little one).

Please I need help with this! Thank you a lot!

**Comment by Hopding** [comment]
Hello @aureliopetrone. I'm no Android expert, but I'll help as best I can.

I don't _think_ this is an issue with `react-native-pdf-lib` (but I could be wrong). This looks like a memory issue in your app. The error message seems to be indicating a couple of things:
1. Your app is allowed a maximum of `536 MB` of RAM (or `536870912` bytes).
2. You have `108 KB` left until you get an OOM error (presumably because you've used up all the rest).
3. `react-native-pdf-lib` is trying to allocate `262 KB` to make your PDF. But that's more than is available, so it fails.

If this analysis is correct, then your app must be using a ton of RAM. `535 MB` or more. Can you try to profile your app in Android Studio and see how much memory you are using?

Also, are you developing this app for iOS as well? If so, have you run into any issues on that platform?

**Comment by inh556** [comment]
If I have a list of line needed to be rendered on the PDF page, how can I do it? I tried to pass an array, and tried to use map a list of texts, but neither works.  Should I call drawText() as many times as I need? Thanks.

**Comment by Hopding** [comment]
@inh556 Please create a new issue for the problem you are encountering, and include some code snippets demonstrating what you have tried to do. I'll then be more than happy to answer your question.
