### ISSUE TITLE
Is it support password protection?

### ISSUE THREAD

**Issue by fukuball** [Hopding/react-native-pdf-lib#41]
Is it support password protection? I didn't see the option on the document.

**Comment by Hopding** [comment]
Hello @fukuball!

`react-native-pdf-lib` does not currently support reading or writing encrypted documents. However, since both of the underlying libraries (for [iOS](https://github.com/galkahana/PDF-Writer) and [Android](https://github.com/TomRoush/PdfBox-Android)) support encryption, it would be possible to implement this feature.

If you (or anybody else) would like to work on a PR for this, I'm happy to provide suggestions/advice.

**Comment by prathammehta** [comment]
Hi @Hopding,

I'd love to work on this and submit a PR. I haven't worked with these underlying libraries before. Could you point me in the right direction?

**Comment by thekevinbrown** [comment]
Hey @prathammehta, in the right direction of what exactly?

The way I'd implement this is first by looking at the implementation this functionality in both of the PDF libraries used, figure out what options need to be passed to them to enable what you need, then finally figure out how a user can pass that in from Javascript.

You'll then just need to pass down the values.
