### ISSUE TITLE
No glyph for U+000A in font courier

### ISSUE THREAD

**Issue by lylest** [Hopding/react-native-pdf-lib#70]
I am getting this error when I attemptED to create pdf  from text that has new line

**Comment by lylest** [comment]
There is now way to create new line for example if I want to generate PDF from the long text from database it's not possible there is no way to add new line the only demonstrated example have used only single line text which is not practically in actually use

**Comment by thekevinbrown** [comment]
If you use a different font that has a glyph for the end of line character you should be able to make it work.

**Comment by lylest** [comment]
I tried two fonts can you send me the working font

**Comment by thekevinbrown** [comment]
Hi @lylest, 

I wanted to apologise for sending you down a rabbit hole that wasn't productive. I've tried this myself today and cannot find a way to make it work with line breaks.

The library does not currently have very rich layout capabilities, it expects you to give it a rectangle and fill with short amounts of content. This is great for things like photo books with small amounts of text in them (what I use this lib for) where we're specifying the layout to it, but obviously would not work well for your use case.

Improving the text layout capabilities would absolutely be something I'd accept a PR for if you're willing to contribute to it, otherwise I'd suggest looking into other libraries to solve your problem.

Sorry again for the bad steer, I was pretty sure this would work and it just doesn't. :-(

**Comment by lylest** [comment]
Thank you for your email and you did the great job making this library
though it's still lack some features I would like to contribute but I never
really built even a library I am not sure if my skills can help to make it
more better please let me know if there is anything that I can do to help I
would really love to be a part of it

**Comment by thekevinbrown** [comment]
I'll go ahead and close this issue as there's not much to do except enhance the overall text layout capabilities of this library, which I'm not going to have time or space to do anytime soon. If anyone wants to create a PR for this it'd be very welcome.

**Comment by lylest** [comment]
any solution for this?

**Comment by thekevinbrown** [comment]
Just the one I mentioned above: build it.
