### ISSUE TITLE
how styling works

### ISSUE THREAD

**Issue by sikky99** [Hopding/react-native-pdf-lib#79]
Can i style with Jsx , html or is there is any documentation for react-native-pdf-lib

**Comment by thekevinbrown** [comment]
Hey there,

The documentation is the readme. Styling is done when you do the draw commands, e.g.

```
.drawRectangle({
    x: 75,
    y: 75,
    width: 50,
    height: 50,
    color: '#99FFCC',
  });
```

HTML is not supported because this is a way to directly use a PDF drawing library, not an HTML to PDF converter. If you want one of those, there's one here: https://github.com/christopherdro/react-native-html-to-pdf

**Comment by thekevinbrown** [comment]
I'll go ahead and close this as we're not intending to support CSS or HTML within the scope of this library any time soon.
